[package]
name = "ping_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
ping = "0.5"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
